"""Open camera RAW files (DNG, CR2, NEF, ARW, ...) as linear float tensors that keep the sensor's 16-bit precision, using rawpy

Docs: https://docs.fast.ai/vision.raw.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/09d_vision.raw.ipynb.

# %% auto #0
__all__ = ['raw_extensions', 'get_raw_files', 'TensorRawImage', 'RawImageCreate', 'RawImageBlock']

# %% ../../nbs/09d_vision.raw.ipynb #07a1e151
from ..basics import *
from .all import *

import rawpy

# %% ../../nbs/09d_vision.raw.ipynb #6c2824e6
raw_extensions = {'.3fr','.arw','.cr2','.cr3','.crw','.dcr','.dng','.erf','.iiq','.k25','.kdc','.mef','.mos','.mrw',
                  '.nef','.nrw','.orf','.pef','.raf','.rw2','.rwl','.sr2','.srf','.srw'}

# %% ../../nbs/09d_vision.raw.ipynb #20f0e947
def get_raw_files(path, recurse=True, folders=None):
    "Get RAW camera files in `path` recursively, only in `folders`, if specified."
    return get_files(path, extensions=raw_extensions, recurse=recurse, folders=folders)

# %% ../../nbs/09d_vision.raw.ipynb #0d1d0228
_raw_defaults = dict(gamma=(1,1), no_auto_bright=True, output_bps=16, use_camera_wb=True)

# %% ../../nbs/09d_vision.raw.ipynb #a573a0e9
class TensorRawImage(TensorImage):
    "A `TensorImage` decoded from a camera RAW file by rawpy: float32, channels first, values in [0,1]"
    @classmethod
    def create(cls, fn:Path|str|bytes, **kwargs):
        "Open RAW file `fn` (path or bytes) and postprocess it with rawpy `kwargs` (defaults: linear, 16-bit, camera white balance)"
        p = {**_raw_defaults, **kwargs}
        with rawpy.imread(io.BytesIO(fn) if isinstance(fn,bytes) else str(fn)) as raw: x = raw.postprocess(**p)
        return cls(torch.from_numpy(x.astype(np.float32)/(2**p['output_bps']-1)).permute(2,0,1))

# %% ../../nbs/09d_vision.raw.ipynb #3037e37c
@IntToFloatTensor
def encodes(self, o:TensorRawImage): return o
@IntToFloatTensor
def decodes(self, o:TensorRawImage): return o.clamp(0.,1.)

# %% ../../nbs/09d_vision.raw.ipynb #2246f350
class RawImageCreate(Transform):
    "Open a RAW file as a `TensorRawImage`, passing `kwargs` to `TensorRawImage.create`"
    input_types = (Path,str,bytes)
    def __init__(self, **kwargs): self.kwargs = kwargs
    def encodes(self, fn:Path|str|bytes): return TensorRawImage.create(fn, **self.kwargs)

def RawImageBlock(**kwargs):
    "A `TransformBlock` for RAW camera images; `kwargs` are passed to `TensorRawImage.create`"
    return TransformBlock(type_tfms=RawImageCreate(**kwargs), batch_tfms=IntToFloatTensor)
